export enum Paths {
  Root = '/',
  Project1 = '/18',
  Project2 = '/project2',
  Project3 = '/project3',
  Project4 = '/project4',
  Project5 = '/project5',
  Project6 = '/project6',
  Project7 = '/project7',
  calculator = '/80',
  Project82 = '/82',
  chart = '/111',
  memes = '/69',
  figma = '/figma',
}
