export enum Paths {
  Root = '/',
  GetStarted = '/get-started',
  StartNow = '',
  Login = '/login',
  Register = '/register',
  WorkspaceConfig = '/workspace-config',
  WorkspaceConfig1 = '/workspace-config/1',
  WorkspaceConfig2 = '/workspace-config/1/2',
  WorkspaceConfig3 = '/workspace-config/1/2/3',
  WorkspaceConfig4 = '/workspace-config/1/2/3/4',
  WorkspaceConfig5 = '/workspace-config/1/2/3/4/5',
  Dashboard = '/dashboard',
  Spaces = '/spaces',
  Chat = '/chat',
  Brainstorming = '/brainstorming',
  Calendar = '/calendar',
  TimeTracking = '/time-tracking',
  ReportGeneration = '/report-generation',
  Settings = '/settings',
}
